name: Deploy to GitHub Pages

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]  # Triggers on push to the main branch
  pull_request:
    branches: [ "main" ]  # Optional: Runs on pull requests to main

  workflow_dispatch:  # Allows for manual workflow runs

jobs:
  deploy:
    runs-on: ubuntu-latest  # The type of runner

    steps:
      # Checkout the repository code
      - uses: actions/checkout@v4

      # Optional: Install dependencies if your project needs to be built (e.g., if using Jekyll, Gatsby, Hugo, etc.)
      - name: Install dependencies
        run: |
          npm install  # Or `bundle install` for Jekyll, or any other installation command your project requires

      # Optional: Build the site (if using a static site generator)
      - name: Build the website
        run: |
          npm run build  # Use the appropriate build command, like `jekyll build` or `gatsby build`

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3  # GitHub Pages deploy action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Directory to publish, change this if your output directory is different (e.g., `public` for Hugo)
